### ISSUE TITLE
SSL wrong version number

### ISSUE THREAD

**Issue by TheZoker** [bandundu/email-archiver#12]
When I try to archive my mail, I get this error:

```
2024-03-14 14:42:38,964 - ERROR - Exception details: Traceback (most recent call last):
  File "/app/email_archiver.py", line 103, in fetch_and_archive_emails
    client = imaplib.IMAP4_SSL(server, port)
  File "/usr/local/lib/python3.9/imaplib.py", line 1324, in __init__
    IMAP4.__init__(self, host, port, timeout)
  File "/usr/local/lib/python3.9/imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.9/imaplib.py", line 1337, in open
    IMAP4.open(self, host, port, timeout)
  File "/usr/local/lib/python3.9/imaplib.py", line 312, in open
    self.sock = self._create_socket(timeout)
  File "/usr/local/lib/python3.9/imaplib.py", line 1328, in _create_socket
    return self.ssl_context.wrap_socket(sock,
  File "/usr/local/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
```

I use IMAP with the port 143. 

These are the ports provided by my hoster:

![image](https://github.com/bandundu/email-archiver/assets/1368405/4d99817e-97e0-40ae-a5ca-50ebb825fb28)

Which combination should I use to get this working? Thanks!

**Comment by bandundu** [comment]
For now, the application does not support unsecured connections. This is somethin I will add. For IMAP or POP3 with SSL/TLS should work.

**Comment by TheZoker** [comment]
Alright, thanks for the clarification.

I now tried IMAP with 993. 

I now get this error:
```
2024-03-14 14:58:52,630 - ERROR - An error occurred during email archiving for account 1: expected string or bytes-like object
2024-03-14 14:58:52,631 - ERROR - Exception details: Traceback (most recent call last):
  File "/app/email_archiver.py", line 160, in fetch_and_archive_emails
    recipients_parts = email.header.decode_header(email_message['To'])
  File "/usr/local/lib/python3.9/email/header.py", line 80, in decode_header
    if not ecre.search(header):
TypeError: expected string or bytes-like object
```

And the script stops. 

I have a lot of these lines in the logs:
```
2024-03-14 14:58:52,470 - INFO - Inserted email with UID b'18864' for account 1 into the database.
2024-03-14 14:58:52,505 - INFO - Inserted email with UID b'18865' for account 1 into the database.
2024-03-14 14:58:52,540 - INFO - Inserted email with UID b'18866' for account 1 into the database.
2024-03-14 14:58:52,559 - INFO - Inserted email with UID b'18868' for account 1 into the database.
2024-03-14 14:58:52,594 - INFO - Inserted email with UID b'18870' for account 1 into the database.
2024-03-14 14:58:52,613 - INFO - Inserted email with UID b'18874' for account 1 into the database.
```

But the dashboard still shows 0 archived emails:
![image](https://github.com/bandundu/email-archiver/assets/1368405/d63ab8da-bb28-443e-9e67-488538c1314a)

**Comment by bandundu** [comment]
Really interesting. Out of curiosity, how would you get emails without TO header? Did not expect this.

Should be fixed in latest release, please retry and give me feedback

**Comment by TheZoker** [comment]
I think that can happen when you use BCC without TO. 

Looks good, I think this issue is fixed. 

I now have this error:
```
2024-03-18 07:19:30,763 - ERROR - Exception details: Traceback (most recent call last):
  File "/app/email_archiver.py", line 155, in fetch_and_archive_emails
    decoded_sender_parts.append(part.decode(encoding or 'utf-8'))
LookupError: unknown encoding: unknown-8bit
```

I wonder why no mail has been archived yet. Is the operation only successful, if there is no error during the process? Because the logs show a lot of 
```
2024-03-18 07:24:32,563 - INFO - Inserted email with UID b'18705' for account 1 into the database.
```
but still nothing in the dashboard.

**Comment by bandundu** [comment]
@TheZoker created a seperate issue #14  as the initial bug seems to be solved.
