### ISSUE TITLE
ERROR - An error occurred during email archiving for account 1: expected string or bytes-like object

### ISSUE THREAD

**Issue by Node815** [bandundu/email-archiver#18]
Log from start of  Account 1 to Account 2:

```2024-03-18 14:37:34,925 - INFO - Found 220 emails for account 1.

2024-03-18 14:37:39,288 - ERROR - An error occurred during email archiving for account 1: expected string or bytes-like object

2024-03-18 14:37:39,288 - ERROR - Exception details: Traceback (most recent call last):

  File "/app/email_archiver.py", line 160, in fetch_and_archive_emails

    recipients_parts = email.header.decode_header(email_message['To'])

  File "/usr/local/lib/python3.9/email/header.py", line 80, in decode_header

    if not ecre.search(header):

TypeError: expected string or bytes-like object

2024-03-18 14:37:39,289 - INFO - Started email archiving for account 2.

2024-03-18 14:37:39,820 - ERROR - An error occurred during email archiving for account 1: expected string or bytes-like object

2024-03-18 14:37:39,820 - ERROR - Exception details: Traceback (most recent call last):

  File "/app/email_archiver.py", line 160, in fetch_and_archive_emails

    recipients_parts = email.header.decode_header(email_message['To'])

  File "/usr/local/lib/python3.9/email/header.py", line 80, in decode_header

    if not ecre.search(header):

TypeError: expected string or bytes-like object

2024-03-18 14:37:39,820 - INFO - Started email archiving for account 2.```

**Comment by bandundu** [comment]
I am closing this issue as I want to have a first stable version and then deploy with docker. I would greatly appreciate if you could use the app bare-metal and support further by opening issues.

Thank you
Charles
