### ISSUE TITLE
Idea: offer option to periodically fetch new emails

### ISSUE THREAD

**Issue by airdogvan** [bandundu/email-archiver#19]
Title about says it all: after initial run, new emails on server are not fetched.  Would be nice if could fetch new mails every day/hour, etc.
Could then be used as backup for servers mails.

**Comment by bandundu** [comment]
Thanks for the suggestion however the application should already do this. Can you check logs and give me an excerpt?

**Comment by airdogvan** [comment]
The logs said "incorrect username or password" which is not right (maybe special character in password?).
I deleted the account, restarted docker-compose and this is the result:
sorry for the long log.
Please note that the emails are still listed although I already deleted the account.

```
web_1  | 2024-03-19 17:21:34,794 - ERROR - An error occurred during email archiving for account 1: b'Incorrect username or password.'
web_1  | 2024-03-19 17:21:34,794 - ERROR - An error occurred during email archiving for account 1: b'Incorrect username or password.'
web_1  | 2024-03-19 17:21:34,794 - ERROR - Exception details: Traceback (most recent call last):
web_1  |   File "/app/email_archiver.py", line 105, in fetch_and_archive_emails
web_1  |     client.login(username, password)
web_1  |   File "/usr/local/lib/python3.9/imaplib.py", line 612, in login
web_1  |     raise self.error(dat[-1])
web_1  | imaplib.IMAP4.error: b'Incorrect username or password.'
web_1  | 
web_1  | 2024-03-19 17:21:34,794 - ERROR - Exception details: Traceback (most recent call last):
web_1  |   File "/app/email_archiver.py", line 105, in fetch_and_archive_emails
web_1  |     client.login(username, password)
web_1  |   File "/usr/local/lib/python3.9/imaplib.py", line 612, in login
web_1  |     raise self.error(dat[-1])
web_1  | imaplib.IMAP4.error: b'Incorrect username or password.'
web_1  | 
web_1  | 2024-03-19 17:21:34,795 - INFO - Email archiving cycle completed.
web_1  | 2024-03-19 17:21:34,795 - INFO - Email archiving cycle completed.
web_1  | 2024-03-19 17:21:46,814 - INFO - 172.19.0.5 - - [19/Mar/2024 17:21:46] "GET / HTTP/1.1" 200 -
web_1  | 2024-03-19 17:21:49,625 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:21:49,625 - INFO - Retrieved 1 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:21:49,629 - INFO - 172.19.0.5 - - [19/Mar/2024 17:21:49] "GET /list_accounts HTTP/1.1" 200 -
web_1  | 2024-03-19 17:21:51,725 - INFO - Fetching account details for account ID 1.
web_1  | 2024-03-19 17:21:51,725 - INFO - Account details fetched successfully for account ID 1.
web_1  | 2024-03-19 17:21:51,728 - INFO - 172.19.0.5 - - [19/Mar/2024 17:21:51] "GET /update_account/1 HTTP/1.1" 200 -
web_1  | 2024-03-19 17:24:00,691 - INFO - Updating account 1 with email airdog@fastmail.com.
web_1  | 2024-03-19 17:24:00,696 - INFO - Account 1 updated successfully.
web_1  | 2024-03-19 17:24:00,696 - INFO - 172.19.0.5 - - [19/Mar/2024 17:24:00] "POST /update_account/1 HTTP/1.1" 302 -
web_1  | 2024-03-19 17:24:00,713 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:24:00,713 - INFO - Retrieved 1 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:24:00,713 - INFO - 172.19.0.5 - - [19/Mar/2024 17:24:00] "GET /list_accounts HTTP/1.1" 200 -
web_1  | 2024-03-19 17:24:00,903 - INFO - 172.19.0.5 - - [19/Mar/2024 17:24:00] "GET /favicon.ico HTTP/1.1" 404 -
web_1  | 2024-03-19 17:24:08,827 - INFO - 172.19.0.5 - - [19/Mar/2024 17:24:08] "GET / HTTP/1.1" 200 -
web_1  | 2024-03-19 17:24:47,603 - INFO - 172.19.0.5 - - [19/Mar/2024 17:24:47] "GET / HTTP/1.1" 200 -
web_1  | 2024-03-19 17:24:47,757 - INFO - 172.19.0.5 - - [19/Mar/2024 17:24:47] "GET /favicon.ico HTTP/1.1" 404 -
web_1  | 2024-03-19 17:26:19,622 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:19,622 - INFO - Retrieved 1 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:19,622 - INFO - 172.19.0.5 - - [19/Mar/2024 17:26:19] "GET /list_accounts HTTP/1.1" 200 -
web_1  | 2024-03-19 17:26:22,226 - INFO - Fetching account details for account ID 1.
web_1  | 2024-03-19 17:26:22,226 - INFO - Account details fetched successfully for account ID 1.
web_1  | 2024-03-19 17:26:22,228 - INFO - 172.19.0.5 - - [19/Mar/2024 17:26:22] "GET /delete_account/1 HTTP/1.1" 200 -
web_1  | 2024-03-19 17:26:24,259 - INFO - Deleting account 1.
web_1  | 2024-03-19 17:26:24,267 - INFO - Account 1 deleted successfully.
web_1  | 2024-03-19 17:26:24,268 - INFO - 172.19.0.5 - - [19/Mar/2024 17:26:24] "POST /delete_account/1 HTTP/1.1" 302 -
web_1  | 2024-03-19 17:26:24,327 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:24,328 - INFO - Retrieved 0 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:24,328 - INFO - 172.19.0.5 - - [19/Mar/2024 17:26:24] "GET /list_accounts HTTP/1.1" 200 -
web_1  | 2024-03-19 17:26:26,252 - INFO - 172.19.0.5 - - [19/Mar/2024 17:26:26] "GET / HTTP/1.1" 200 -
web_1  | 2024-03-19 17:26:34,894 - INFO - Starting email archiving cycle...
web_1  | 2024-03-19 17:26:34,894 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:34,894 - INFO - Retrieved 0 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:34,894 - INFO - Email archiving cycle completed.
web_1  | 2024-03-19 17:26:34,894 - INFO - Starting email archiving cycle...
web_1  | 2024-03-19 17:26:34,895 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:34,895 - INFO - Retrieved 0 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:34,895 - INFO - Email archiving cycle completed.
web_1  | 2024-03-19 17:26:43,391 - INFO - 172.19.0.5 - - [19/Mar/2024 17:26:43] "GET / HTTP/1.1" 200 -
web_1  | 2024-03-19 17:26:54,461 - INFO - Database already exists.
web_1  | 2024-03-19 17:26:54,461 - INFO - Starting email archiving cycle...
web_1  | 2024-03-19 17:26:54,462 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  |  * Serving Flask app 'app'
web_1  |  * Debug mode: on
web_1  | 2024-03-19 17:26:54,462 - INFO - Retrieved 0 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:54,462 - INFO - Email archiving cycle completed.
web_1  | 2024-03-19 17:26:54,466 - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
web_1  |  * Running on all addresses (0.0.0.0)
web_1  |  * Running on http://127.0.0.1:5000
web_1  |  * Running on http://172.19.0.14:5000
web_1  | 2024-03-19 17:26:54,467 - INFO - Press CTRL+C to quit
web_1  | 2024-03-19 17:26:54,467 - INFO -  * Restarting with stat
web_1  | 2024-03-19 17:26:54,603 - INFO - Database already exists.
web_1  | 2024-03-19 17:26:54,603 - INFO - Starting email archiving cycle...
web_1  | 2024-03-19 17:26:54,603 - INFO - Fetching all IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:54,604 - INFO - Retrieved 0 IMAP/POP3 accounts from the database.
web_1  | 2024-03-19 17:26:54,604 - INFO - Email archiving cycle completed.
web_1  | 2024-03-19 17:26:54,606 - WARNING -  * Debugger is active!
web_1  | 2024-03-19 17:26:54,606 - INFO -  * Debugger PIN: 919-828-271
```

**Comment by bandundu** [comment]
Thank you for sharing will look into this

**Comment by bandundu** [comment]
Functionality to add interval for updating was added with last commit
