### ISSUE TITLE
Backend not starting

### ISSUE THREAD

**Issue by Trilis29** [bandundu/email-archiver#27]
Backend not starting, throwing errors

`INFO:     24.06.2024 13:30:44.650 - Using preset Fernet key: eL2czOOOrVS5RUnxle5bE2mUpwNp_FQNXkJzctUWW7A=
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from models.database import initialize_database
  File "/home/user/email-archiver/backend/models/database.py", line 9, in <module>
    engine = create_engine(config.DATABASE_URL, pool_size=20)
  File "<string>", line 2, in create_engine
  File "/home/user/email-archiver/backend/.venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/user/email-archiver/backend/.venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 546, in create_engine
    u = _url.make_url(url)
  File "/home/user/email-archiver/backend/.venv/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 846, in make_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Expected string or URL object, got None`

**Comment by the-yrr** [comment]
I have the same problem, the root cause seems to be missing environement variables in config.py

Adding these environment variables should resolve the problem:

>     SECRET_KEY = os.getenv("SECRET_KEY")
>     DATABASE_URL = os.getenv("DATABASE_URL")
>     DATBASE_DIR = os.getenv("DATABASE_DIR")
>     LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

**Comment by jonas-karlsson** [comment]
I had to add this to the .env for it to start.

```
DATABASE_URL=sqlite:///data/database.sqlite
DATABASE_DIR=data
LOG_LEVEL=INFO
```
This creates a data directory in the backend folder and stores the sqlite database there.

**Comment by bandundu** [comment]
Hi this got fixed in with https://github.com/bandundu/email-archiver/commit/97da2392067e1ec19dcf62863ad192586398e76e

KR Charles
